// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/yandexproto/yandex.proto

package yandexproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamInterval int32

const (
	StreamInterval_NO_CONNECTION StreamInterval = 0
	StreamInterval_TRANSLATING   StreamInterval = 10
	StreamInterval_STREAMING     StreamInterval = 20
)

// Enum value maps for StreamInterval.
var (
	StreamInterval_name = map[int32]string{
		0:  "NO_CONNECTION",
		10: "TRANSLATING",
		20: "STREAMING",
	}
	StreamInterval_value = map[string]int32{
		"NO_CONNECTION": 0,
		"TRANSLATING":   10,
		"STREAMING":     20,
	}
)

func (x StreamInterval) Enum() *StreamInterval {
	p := new(StreamInterval)
	*p = x
	return p
}

func (x StreamInterval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamInterval) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_yandexproto_yandex_proto_enumTypes[0].Descriptor()
}

func (StreamInterval) Type() protoreflect.EnumType {
	return &file_internal_yandexproto_yandex_proto_enumTypes[0]
}

func (x StreamInterval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamInterval.Descriptor instead.
func (StreamInterval) EnumDescriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{0}
}

// VIDEO TRANSLATION
type VideoTranslationHelpObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`       // "video_file_url" or "subtitles_file_url"
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=targetUrl,proto3" json:"targetUrl,omitempty"` // raw url to video file or subs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTranslationHelpObject) Reset() {
	*x = VideoTranslationHelpObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationHelpObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationHelpObject) ProtoMessage() {}

func (x *VideoTranslationHelpObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationHelpObject.ProtoReflect.Descriptor instead.
func (*VideoTranslationHelpObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{0}
}

func (x *VideoTranslationHelpObject) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *VideoTranslationHelpObject) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

type VideoTranslationRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Url              string                        `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	DeviceId         *string                       `protobuf:"bytes,4,opt,name=deviceId,proto3,oneof" json:"deviceId,omitempty"`
	FirstRequest     bool                          `protobuf:"varint,5,opt,name=firstRequest,proto3" json:"firstRequest,omitempty"`
	Duration         float64                       `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Unknown0         int32                         `protobuf:"varint,7,opt,name=unknown0,proto3" json:"unknown0,omitempty"`               // 1 1
	Language         string                        `protobuf:"bytes,8,opt,name=language,proto3" json:"language,omitempty"`                // source language code
	ForceSourceLang  bool                          `protobuf:"varint,9,opt,name=forceSourceLang,proto3" json:"forceSourceLang,omitempty"` // 0 - auto, 1 - user-selected
	Unknown1         int32                         `protobuf:"varint,10,opt,name=unknown1,proto3" json:"unknown1,omitempty"`              // 0 0
	TranslationHelp  []*VideoTranslationHelpObject `protobuf:"bytes,11,rep,name=translationHelp,proto3" json:"translationHelp,omitempty"`
	WasStream        bool                          `protobuf:"varint,13,opt,name=wasStream,proto3" json:"wasStream,omitempty"`
	ResponseLanguage string                        `protobuf:"bytes,14,opt,name=responseLanguage,proto3" json:"responseLanguage,omitempty"`
	Unknown2         int32                         `protobuf:"varint,15,opt,name=unknown2,proto3" json:"unknown2,omitempty"` // 1?
	Unknown3         int32                         `protobuf:"varint,16,opt,name=unknown3,proto3" json:"unknown3,omitempty"` // before april 2025 is 1, now 2
	BypassCache      bool                          `protobuf:"varint,17,opt,name=bypassCache,proto3" json:"bypassCache,omitempty"`
	UseLivelyVoice   bool                          `protobuf:"varint,18,opt,name=useLivelyVoice,proto3" json:"useLivelyVoice,omitempty"`
	VideoTitle       string                        `protobuf:"bytes,19,opt,name=videoTitle,proto3" json:"videoTitle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VideoTranslationRequest) Reset() {
	*x = VideoTranslationRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationRequest) ProtoMessage() {}

func (x *VideoTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationRequest.ProtoReflect.Descriptor instead.
func (*VideoTranslationRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{1}
}

func (x *VideoTranslationRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoTranslationRequest) GetDeviceId() string {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return ""
}

func (x *VideoTranslationRequest) GetFirstRequest() bool {
	if x != nil {
		return x.FirstRequest
	}
	return false
}

func (x *VideoTranslationRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoTranslationRequest) GetUnknown0() int32 {
	if x != nil {
		return x.Unknown0
	}
	return 0
}

func (x *VideoTranslationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *VideoTranslationRequest) GetForceSourceLang() bool {
	if x != nil {
		return x.ForceSourceLang
	}
	return false
}

func (x *VideoTranslationRequest) GetUnknown1() int32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

func (x *VideoTranslationRequest) GetTranslationHelp() []*VideoTranslationHelpObject {
	if x != nil {
		return x.TranslationHelp
	}
	return nil
}

func (x *VideoTranslationRequest) GetWasStream() bool {
	if x != nil {
		return x.WasStream
	}
	return false
}

func (x *VideoTranslationRequest) GetResponseLanguage() string {
	if x != nil {
		return x.ResponseLanguage
	}
	return ""
}

func (x *VideoTranslationRequest) GetUnknown2() int32 {
	if x != nil {
		return x.Unknown2
	}
	return 0
}

func (x *VideoTranslationRequest) GetUnknown3() int32 {
	if x != nil {
		return x.Unknown3
	}
	return 0
}

func (x *VideoTranslationRequest) GetBypassCache() bool {
	if x != nil {
		return x.BypassCache
	}
	return false
}

func (x *VideoTranslationRequest) GetUseLivelyVoice() bool {
	if x != nil {
		return x.UseLivelyVoice
	}
	return false
}

func (x *VideoTranslationRequest) GetVideoTitle() string {
	if x != nil {
		return x.VideoTitle
	}
	return ""
}

type VideoTranslationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Duration      *float64               `protobuf:"fixed64,2,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	RemainingTime *int32                 `protobuf:"varint,5,opt,name=remainingTime,proto3,oneof" json:"remainingTime,omitempty"`
	Unknown0      *int32                 `protobuf:"varint,6,opt,name=unknown0,proto3,oneof" json:"unknown0,omitempty"`
	TranslationId string                 `protobuf:"bytes,7,opt,name=translationId,proto3" json:"translationId,omitempty"`
	Language      *string                `protobuf:"bytes,8,opt,name=language,proto3,oneof" json:"language,omitempty"`
	Message       *string                `protobuf:"bytes,9,opt,name=message,proto3,oneof" json:"message,omitempty"`
	IsLivelyVoice bool                   `protobuf:"varint,10,opt,name=isLivelyVoice,proto3" json:"isLivelyVoice,omitempty"`
	Unknown2      *int32                 `protobuf:"varint,11,opt,name=unknown2,proto3,oneof" json:"unknown2,omitempty"`
	ShouldRetry   *int32                 `protobuf:"varint,12,opt,name=shouldRetry,proto3,oneof" json:"shouldRetry,omitempty"`
	Unknown3      *int32                 `protobuf:"varint,13,opt,name=unknown3,proto3,oneof" json:"unknown3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTranslationResponse) Reset() {
	*x = VideoTranslationResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationResponse) ProtoMessage() {}

func (x *VideoTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationResponse.ProtoReflect.Descriptor instead.
func (*VideoTranslationResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{2}
}

func (x *VideoTranslationResponse) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *VideoTranslationResponse) GetDuration() float64 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *VideoTranslationResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoTranslationResponse) GetRemainingTime() int32 {
	if x != nil && x.RemainingTime != nil {
		return *x.RemainingTime
	}
	return 0
}

func (x *VideoTranslationResponse) GetUnknown0() int32 {
	if x != nil && x.Unknown0 != nil {
		return *x.Unknown0
	}
	return 0
}

func (x *VideoTranslationResponse) GetTranslationId() string {
	if x != nil {
		return x.TranslationId
	}
	return ""
}

func (x *VideoTranslationResponse) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *VideoTranslationResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *VideoTranslationResponse) GetIsLivelyVoice() bool {
	if x != nil {
		return x.IsLivelyVoice
	}
	return false
}

func (x *VideoTranslationResponse) GetUnknown2() int32 {
	if x != nil && x.Unknown2 != nil {
		return *x.Unknown2
	}
	return 0
}

func (x *VideoTranslationResponse) GetShouldRetry() int32 {
	if x != nil && x.ShouldRetry != nil {
		return *x.ShouldRetry
	}
	return 0
}

func (x *VideoTranslationResponse) GetUnknown3() int32 {
	if x != nil && x.Unknown3 != nil {
		return *x.Unknown3
	}
	return 0
}

type VideoTranslationCacheItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RemainingTime *int32                 `protobuf:"varint,2,opt,name=remainingTime,proto3,oneof" json:"remainingTime,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Unknown0      *int32                 `protobuf:"varint,4,opt,name=unknown0,proto3,oneof" json:"unknown0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTranslationCacheItem) Reset() {
	*x = VideoTranslationCacheItem{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationCacheItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationCacheItem) ProtoMessage() {}

func (x *VideoTranslationCacheItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationCacheItem.ProtoReflect.Descriptor instead.
func (*VideoTranslationCacheItem) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{3}
}

func (x *VideoTranslationCacheItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoTranslationCacheItem) GetRemainingTime() int32 {
	if x != nil && x.RemainingTime != nil {
		return *x.RemainingTime
	}
	return 0
}

func (x *VideoTranslationCacheItem) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *VideoTranslationCacheItem) GetUnknown0() int32 {
	if x != nil && x.Unknown0 != nil {
		return *x.Unknown0
	}
	return 0
}

type VideoTranslationCacheRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Url              string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Duration         float64                `protobuf:"fixed64,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Language         string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	ResponseLanguage string                 `protobuf:"bytes,4,opt,name=responseLanguage,proto3" json:"responseLanguage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VideoTranslationCacheRequest) Reset() {
	*x = VideoTranslationCacheRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationCacheRequest) ProtoMessage() {}

func (x *VideoTranslationCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationCacheRequest.ProtoReflect.Descriptor instead.
func (*VideoTranslationCacheRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{4}
}

func (x *VideoTranslationCacheRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoTranslationCacheRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoTranslationCacheRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *VideoTranslationCacheRequest) GetResponseLanguage() string {
	if x != nil {
		return x.ResponseLanguage
	}
	return ""
}

type VideoTranslationCacheResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Default       *VideoTranslationCacheItem `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Cloning       *VideoTranslationCacheItem `protobuf:"bytes,2,opt,name=cloning,proto3" json:"cloning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoTranslationCacheResponse) Reset() {
	*x = VideoTranslationCacheResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationCacheResponse) ProtoMessage() {}

func (x *VideoTranslationCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationCacheResponse.ProtoReflect.Descriptor instead.
func (*VideoTranslationCacheResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{5}
}

func (x *VideoTranslationCacheResponse) GetDefault() *VideoTranslationCacheItem {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *VideoTranslationCacheResponse) GetCloning() *VideoTranslationCacheItem {
	if x != nil {
		return x.Cloning
	}
	return nil
}

type AudioBufferObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioFile     []byte                 `protobuf:"bytes,2,opt,name=audioFile,proto3" json:"audioFile,omitempty"`
	FileId        string                 `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioBufferObject) Reset() {
	*x = AudioBufferObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioBufferObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioBufferObject) ProtoMessage() {}

func (x *AudioBufferObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioBufferObject.ProtoReflect.Descriptor instead.
func (*AudioBufferObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{6}
}

func (x *AudioBufferObject) GetAudioFile() []byte {
	if x != nil {
		return x.AudioFile
	}
	return nil
}

func (x *AudioBufferObject) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type PartialAudioBufferObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioFile     []byte                 `protobuf:"bytes,2,opt,name=audioFile,proto3" json:"audioFile,omitempty"`
	ChunkId       int32                  `protobuf:"varint,1,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialAudioBufferObject) Reset() {
	*x = PartialAudioBufferObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialAudioBufferObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialAudioBufferObject) ProtoMessage() {}

func (x *PartialAudioBufferObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialAudioBufferObject.ProtoReflect.Descriptor instead.
func (*PartialAudioBufferObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{7}
}

func (x *PartialAudioBufferObject) GetAudioFile() []byte {
	if x != nil {
		return x.AudioFile
	}
	return nil
}

func (x *PartialAudioBufferObject) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

type ChunkAudioObject struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	AudioBuffer      *PartialAudioBufferObject `protobuf:"bytes,1,opt,name=audioBuffer,proto3" json:"audioBuffer,omitempty"`
	AudioPartsLength int32                     `protobuf:"varint,2,opt,name=audioPartsLength,proto3" json:"audioPartsLength,omitempty"`
	FileId           string                    `protobuf:"bytes,3,opt,name=fileId,proto3" json:"fileId,omitempty"`
	Version          int32                     `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChunkAudioObject) Reset() {
	*x = ChunkAudioObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkAudioObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkAudioObject) ProtoMessage() {}

func (x *ChunkAudioObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkAudioObject.ProtoReflect.Descriptor instead.
func (*ChunkAudioObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkAudioObject) GetAudioBuffer() *PartialAudioBufferObject {
	if x != nil {
		return x.AudioBuffer
	}
	return nil
}

func (x *ChunkAudioObject) GetAudioPartsLength() int32 {
	if x != nil {
		return x.AudioPartsLength
	}
	return 0
}

func (x *ChunkAudioObject) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChunkAudioObject) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VideoTranslationAudioRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TranslationId    string                 `protobuf:"bytes,1,opt,name=translationId,proto3" json:"translationId,omitempty"`
	Url              string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	PartialAudioInfo *ChunkAudioObject      `protobuf:"bytes,4,opt,name=partialAudioInfo,proto3,oneof" json:"partialAudioInfo,omitempty"`
	AudioInfo        *AudioBufferObject     `protobuf:"bytes,6,opt,name=audioInfo,proto3,oneof" json:"audioInfo,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VideoTranslationAudioRequest) Reset() {
	*x = VideoTranslationAudioRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationAudioRequest) ProtoMessage() {}

func (x *VideoTranslationAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationAudioRequest.ProtoReflect.Descriptor instead.
func (*VideoTranslationAudioRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{9}
}

func (x *VideoTranslationAudioRequest) GetTranslationId() string {
	if x != nil {
		return x.TranslationId
	}
	return ""
}

func (x *VideoTranslationAudioRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoTranslationAudioRequest) GetPartialAudioInfo() *ChunkAudioObject {
	if x != nil {
		return x.PartialAudioInfo
	}
	return nil
}

func (x *VideoTranslationAudioRequest) GetAudioInfo() *AudioBufferObject {
	if x != nil {
		return x.AudioInfo
	}
	return nil
}

type VideoTranslationAudioResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RemainingChunks []string               `protobuf:"bytes,2,rep,name=remainingChunks,proto3" json:"remainingChunks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoTranslationAudioResponse) Reset() {
	*x = VideoTranslationAudioResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTranslationAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTranslationAudioResponse) ProtoMessage() {}

func (x *VideoTranslationAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTranslationAudioResponse.ProtoReflect.Descriptor instead.
func (*VideoTranslationAudioResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{10}
}

func (x *VideoTranslationAudioResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *VideoTranslationAudioResponse) GetRemainingChunks() []string {
	if x != nil {
		return x.RemainingChunks
	}
	return nil
}

// SUBTITLES
type SubtitlesObject struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Language           string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Url                string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Unknown0           int32                  `protobuf:"varint,3,opt,name=unknown0,proto3" json:"unknown0,omitempty"`
	TranslatedLanguage string                 `protobuf:"bytes,4,opt,name=translatedLanguage,proto3" json:"translatedLanguage,omitempty"`
	TranslatedUrl      string                 `protobuf:"bytes,5,opt,name=translatedUrl,proto3" json:"translatedUrl,omitempty"`
	Unknown1           int32                  `protobuf:"varint,6,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	Unknown2           int32                  `protobuf:"varint,7,opt,name=unknown2,proto3" json:"unknown2,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubtitlesObject) Reset() {
	*x = SubtitlesObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitlesObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitlesObject) ProtoMessage() {}

func (x *SubtitlesObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitlesObject.ProtoReflect.Descriptor instead.
func (*SubtitlesObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{11}
}

func (x *SubtitlesObject) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitlesObject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubtitlesObject) GetUnknown0() int32 {
	if x != nil {
		return x.Unknown0
	}
	return 0
}

func (x *SubtitlesObject) GetTranslatedLanguage() string {
	if x != nil {
		return x.TranslatedLanguage
	}
	return ""
}

func (x *SubtitlesObject) GetTranslatedUrl() string {
	if x != nil {
		return x.TranslatedUrl
	}
	return ""
}

func (x *SubtitlesObject) GetUnknown1() int32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

func (x *SubtitlesObject) GetUnknown2() int32 {
	if x != nil {
		return x.Unknown2
	}
	return 0
}

type SubtitlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitlesRequest) Reset() {
	*x = SubtitlesRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitlesRequest) ProtoMessage() {}

func (x *SubtitlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitlesRequest.ProtoReflect.Descriptor instead.
func (*SubtitlesRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{12}
}

func (x *SubtitlesRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubtitlesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SubtitlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waiting       bool                   `protobuf:"varint,1,opt,name=waiting,proto3" json:"waiting,omitempty"`
	Subtitles     []*SubtitlesObject     `protobuf:"bytes,2,rep,name=subtitles,proto3" json:"subtitles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitlesResponse) Reset() {
	*x = SubtitlesResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitlesResponse) ProtoMessage() {}

func (x *SubtitlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitlesResponse.ProtoReflect.Descriptor instead.
func (*SubtitlesResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{13}
}

func (x *SubtitlesResponse) GetWaiting() bool {
	if x != nil {
		return x.Waiting
	}
	return false
}

func (x *SubtitlesResponse) GetSubtitles() []*SubtitlesObject {
	if x != nil {
		return x.Subtitles
	}
	return nil
}

// STREAM TRANSLATION
type StreamTranslationObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTranslationObject) Reset() {
	*x = StreamTranslationObject{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTranslationObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTranslationObject) ProtoMessage() {}

func (x *StreamTranslationObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTranslationObject.ProtoReflect.Descriptor instead.
func (*StreamTranslationObject) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{14}
}

func (x *StreamTranslationObject) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StreamTranslationObject) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StreamTranslationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Url              string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Language         string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	ResponseLanguage string                 `protobuf:"bytes,3,opt,name=responseLanguage,proto3" json:"responseLanguage,omitempty"`
	Unknown0         int32                  `protobuf:"varint,5,opt,name=unknown0,proto3" json:"unknown0,omitempty"`
	Unknown1         int32                  `protobuf:"varint,6,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamTranslationRequest) Reset() {
	*x = StreamTranslationRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTranslationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTranslationRequest) ProtoMessage() {}

func (x *StreamTranslationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTranslationRequest.ProtoReflect.Descriptor instead.
func (*StreamTranslationRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{15}
}

func (x *StreamTranslationRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StreamTranslationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *StreamTranslationRequest) GetResponseLanguage() string {
	if x != nil {
		return x.ResponseLanguage
	}
	return ""
}

func (x *StreamTranslationRequest) GetUnknown0() int32 {
	if x != nil {
		return x.Unknown0
	}
	return 0
}

func (x *StreamTranslationRequest) GetUnknown1() int32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

type StreamTranslationResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Interval       StreamInterval           `protobuf:"varint,1,opt,name=interval,proto3,enum=yandex.StreamInterval" json:"interval,omitempty"`
	TranslatedInfo *StreamTranslationObject `protobuf:"bytes,2,opt,name=translatedInfo,proto3,oneof" json:"translatedInfo,omitempty"`
	PingId         *int32                   `protobuf:"varint,3,opt,name=pingId,proto3,oneof" json:"pingId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamTranslationResponse) Reset() {
	*x = StreamTranslationResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTranslationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTranslationResponse) ProtoMessage() {}

func (x *StreamTranslationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTranslationResponse.ProtoReflect.Descriptor instead.
func (*StreamTranslationResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{16}
}

func (x *StreamTranslationResponse) GetInterval() StreamInterval {
	if x != nil {
		return x.Interval
	}
	return StreamInterval_NO_CONNECTION
}

func (x *StreamTranslationResponse) GetTranslatedInfo() *StreamTranslationObject {
	if x != nil {
		return x.TranslatedInfo
	}
	return nil
}

func (x *StreamTranslationResponse) GetPingId() int32 {
	if x != nil && x.PingId != nil {
		return *x.PingId
	}
	return 0
}

type StreamPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PingId        int32                  `protobuf:"varint,1,opt,name=pingId,proto3" json:"pingId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPingRequest) Reset() {
	*x = StreamPingRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPingRequest) ProtoMessage() {}

func (x *StreamPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPingRequest.ProtoReflect.Descriptor instead.
func (*StreamPingRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{17}
}

func (x *StreamPingRequest) GetPingId() int32 {
	if x != nil {
		return x.PingId
	}
	return 0
}

// SESSIONS
type YandexSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YandexSessionRequest) Reset() {
	*x = YandexSessionRequest{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YandexSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YandexSessionRequest) ProtoMessage() {}

func (x *YandexSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YandexSessionRequest.ProtoReflect.Descriptor instead.
func (*YandexSessionRequest) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{18}
}

func (x *YandexSessionRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *YandexSessionRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type YandexSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretKey     string                 `protobuf:"bytes,1,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	Expires       int32                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YandexSessionResponse) Reset() {
	*x = YandexSessionResponse{}
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YandexSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YandexSessionResponse) ProtoMessage() {}

func (x *YandexSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_yandexproto_yandex_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YandexSessionResponse.ProtoReflect.Descriptor instead.
func (*YandexSessionResponse) Descriptor() ([]byte, []int) {
	return file_internal_yandexproto_yandex_proto_rawDescGZIP(), []int{19}
}

func (x *YandexSessionResponse) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *YandexSessionResponse) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

var File_internal_yandexproto_yandex_proto protoreflect.FileDescriptor

const file_internal_yandexproto_yandex_proto_rawDesc = "" +
	"\n" +
	"!internal/yandexproto/yandex.proto\x12\x06yandex\"R\n" +
	"\x1aVideoTranslationHelpObject\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1c\n" +
	"\ttargetUrl\x18\x02 \x01(\tR\ttargetUrl\"\xd1\x04\n" +
	"\x17VideoTranslationRequest\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\bdeviceId\x18\x04 \x01(\tH\x00R\bdeviceId\x88\x01\x01\x12\"\n" +
	"\ffirstRequest\x18\x05 \x01(\bR\ffirstRequest\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\x12\x1a\n" +
	"\bunknown0\x18\a \x01(\x05R\bunknown0\x12\x1a\n" +
	"\blanguage\x18\b \x01(\tR\blanguage\x12(\n" +
	"\x0fforceSourceLang\x18\t \x01(\bR\x0fforceSourceLang\x12\x1a\n" +
	"\bunknown1\x18\n" +
	" \x01(\x05R\bunknown1\x12L\n" +
	"\x0ftranslationHelp\x18\v \x03(\v2\".yandex.VideoTranslationHelpObjectR\x0ftranslationHelp\x12\x1c\n" +
	"\twasStream\x18\r \x01(\bR\twasStream\x12*\n" +
	"\x10responseLanguage\x18\x0e \x01(\tR\x10responseLanguage\x12\x1a\n" +
	"\bunknown2\x18\x0f \x01(\x05R\bunknown2\x12\x1a\n" +
	"\bunknown3\x18\x10 \x01(\x05R\bunknown3\x12 \n" +
	"\vbypassCache\x18\x11 \x01(\bR\vbypassCache\x12&\n" +
	"\x0euseLivelyVoice\x18\x12 \x01(\bR\x0euseLivelyVoice\x12\x1e\n" +
	"\n" +
	"videoTitle\x18\x13 \x01(\tR\n" +
	"videoTitleB\v\n" +
	"\t_deviceId\"\xa2\x04\n" +
	"\x18VideoTranslationResponse\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\x02 \x01(\x01H\x01R\bduration\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12)\n" +
	"\rremainingTime\x18\x05 \x01(\x05H\x02R\rremainingTime\x88\x01\x01\x12\x1f\n" +
	"\bunknown0\x18\x06 \x01(\x05H\x03R\bunknown0\x88\x01\x01\x12$\n" +
	"\rtranslationId\x18\a \x01(\tR\rtranslationId\x12\x1f\n" +
	"\blanguage\x18\b \x01(\tH\x04R\blanguage\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\t \x01(\tH\x05R\amessage\x88\x01\x01\x12$\n" +
	"\risLivelyVoice\x18\n" +
	" \x01(\bR\risLivelyVoice\x12\x1f\n" +
	"\bunknown2\x18\v \x01(\x05H\x06R\bunknown2\x88\x01\x01\x12%\n" +
	"\vshouldRetry\x18\f \x01(\x05H\aR\vshouldRetry\x88\x01\x01\x12\x1f\n" +
	"\bunknown3\x18\r \x01(\x05H\bR\bunknown3\x88\x01\x01B\x06\n" +
	"\x04_urlB\v\n" +
	"\t_durationB\x10\n" +
	"\x0e_remainingTimeB\v\n" +
	"\t_unknown0B\v\n" +
	"\t_languageB\n" +
	"\n" +
	"\b_messageB\v\n" +
	"\t_unknown2B\x0e\n" +
	"\f_shouldRetryB\v\n" +
	"\t_unknown3\"\xc9\x01\n" +
	"\x19VideoTranslationCacheItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12)\n" +
	"\rremainingTime\x18\x02 \x01(\x05H\x00R\rremainingTime\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x01R\amessage\x88\x01\x01\x12\x1f\n" +
	"\bunknown0\x18\x04 \x01(\x05H\x02R\bunknown0\x88\x01\x01B\x10\n" +
	"\x0e_remainingTimeB\n" +
	"\n" +
	"\b_messageB\v\n" +
	"\t_unknown0\"\x94\x01\n" +
	"\x1cVideoTranslationCacheRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x01R\bduration\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12*\n" +
	"\x10responseLanguage\x18\x04 \x01(\tR\x10responseLanguage\"\x99\x01\n" +
	"\x1dVideoTranslationCacheResponse\x12;\n" +
	"\adefault\x18\x01 \x01(\v2!.yandex.VideoTranslationCacheItemR\adefault\x12;\n" +
	"\acloning\x18\x02 \x01(\v2!.yandex.VideoTranslationCacheItemR\acloning\"I\n" +
	"\x11AudioBufferObject\x12\x1c\n" +
	"\taudioFile\x18\x02 \x01(\fR\taudioFile\x12\x16\n" +
	"\x06fileId\x18\x01 \x01(\tR\x06fileId\"R\n" +
	"\x18PartialAudioBufferObject\x12\x1c\n" +
	"\taudioFile\x18\x02 \x01(\fR\taudioFile\x12\x18\n" +
	"\achunkId\x18\x01 \x01(\x05R\achunkId\"\xb4\x01\n" +
	"\x10ChunkAudioObject\x12B\n" +
	"\vaudioBuffer\x18\x01 \x01(\v2 .yandex.PartialAudioBufferObjectR\vaudioBuffer\x12*\n" +
	"\x10audioPartsLength\x18\x02 \x01(\x05R\x10audioPartsLength\x12\x16\n" +
	"\x06fileId\x18\x03 \x01(\tR\x06fileId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"\x82\x02\n" +
	"\x1cVideoTranslationAudioRequest\x12$\n" +
	"\rtranslationId\x18\x01 \x01(\tR\rtranslationId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12I\n" +
	"\x10partialAudioInfo\x18\x04 \x01(\v2\x18.yandex.ChunkAudioObjectH\x00R\x10partialAudioInfo\x88\x01\x01\x12<\n" +
	"\taudioInfo\x18\x06 \x01(\v2\x19.yandex.AudioBufferObjectH\x01R\taudioInfo\x88\x01\x01B\x13\n" +
	"\x11_partialAudioInfoB\f\n" +
	"\n" +
	"_audioInfo\"a\n" +
	"\x1dVideoTranslationAudioResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12(\n" +
	"\x0fremainingChunks\x18\x02 \x03(\tR\x0fremainingChunks\"\xe9\x01\n" +
	"\x0fSubtitlesObject\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\bunknown0\x18\x03 \x01(\x05R\bunknown0\x12.\n" +
	"\x12translatedLanguage\x18\x04 \x01(\tR\x12translatedLanguage\x12$\n" +
	"\rtranslatedUrl\x18\x05 \x01(\tR\rtranslatedUrl\x12\x1a\n" +
	"\bunknown1\x18\x06 \x01(\x05R\bunknown1\x12\x1a\n" +
	"\bunknown2\x18\a \x01(\x05R\bunknown2\"@\n" +
	"\x10SubtitlesRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"d\n" +
	"\x11SubtitlesResponse\x12\x18\n" +
	"\awaiting\x18\x01 \x01(\bR\awaiting\x125\n" +
	"\tsubtitles\x18\x02 \x03(\v2\x17.yandex.SubtitlesObjectR\tsubtitles\"I\n" +
	"\x17StreamTranslationObject\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\xac\x01\n" +
	"\x18StreamTranslationRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12*\n" +
	"\x10responseLanguage\x18\x03 \x01(\tR\x10responseLanguage\x12\x1a\n" +
	"\bunknown0\x18\x05 \x01(\x05R\bunknown0\x12\x1a\n" +
	"\bunknown1\x18\x06 \x01(\x05R\bunknown1\"\xd8\x01\n" +
	"\x19StreamTranslationResponse\x122\n" +
	"\binterval\x18\x01 \x01(\x0e2\x16.yandex.StreamIntervalR\binterval\x12L\n" +
	"\x0etranslatedInfo\x18\x02 \x01(\v2\x1f.yandex.StreamTranslationObjectH\x00R\x0etranslatedInfo\x88\x01\x01\x12\x1b\n" +
	"\x06pingId\x18\x03 \x01(\x05H\x01R\x06pingId\x88\x01\x01B\x11\n" +
	"\x0f_translatedInfoB\t\n" +
	"\a_pingId\"+\n" +
	"\x11StreamPingRequest\x12\x16\n" +
	"\x06pingId\x18\x01 \x01(\x05R\x06pingId\"B\n" +
	"\x14YandexSessionRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\"O\n" +
	"\x15YandexSessionResponse\x12\x1c\n" +
	"\tsecretKey\x18\x01 \x01(\tR\tsecretKey\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x05R\aexpires*C\n" +
	"\x0eStreamInterval\x12\x11\n" +
	"\rNO_CONNECTION\x10\x00\x12\x0f\n" +
	"\vTRANSLATING\x10\n" +
	"\x12\r\n" +
	"\tSTREAMING\x10\x14BBZ@github.com/netnomadd/vot-cli-go/internal/yandexproto;yandexprotob\x06proto3"

var (
	file_internal_yandexproto_yandex_proto_rawDescOnce sync.Once
	file_internal_yandexproto_yandex_proto_rawDescData []byte
)

func file_internal_yandexproto_yandex_proto_rawDescGZIP() []byte {
	file_internal_yandexproto_yandex_proto_rawDescOnce.Do(func() {
		file_internal_yandexproto_yandex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_yandexproto_yandex_proto_rawDesc), len(file_internal_yandexproto_yandex_proto_rawDesc)))
	})
	return file_internal_yandexproto_yandex_proto_rawDescData
}

var file_internal_yandexproto_yandex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_yandexproto_yandex_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_yandexproto_yandex_proto_goTypes = []any{
	(StreamInterval)(0),                   // 0: yandex.StreamInterval
	(*VideoTranslationHelpObject)(nil),    // 1: yandex.VideoTranslationHelpObject
	(*VideoTranslationRequest)(nil),       // 2: yandex.VideoTranslationRequest
	(*VideoTranslationResponse)(nil),      // 3: yandex.VideoTranslationResponse
	(*VideoTranslationCacheItem)(nil),     // 4: yandex.VideoTranslationCacheItem
	(*VideoTranslationCacheRequest)(nil),  // 5: yandex.VideoTranslationCacheRequest
	(*VideoTranslationCacheResponse)(nil), // 6: yandex.VideoTranslationCacheResponse
	(*AudioBufferObject)(nil),             // 7: yandex.AudioBufferObject
	(*PartialAudioBufferObject)(nil),      // 8: yandex.PartialAudioBufferObject
	(*ChunkAudioObject)(nil),              // 9: yandex.ChunkAudioObject
	(*VideoTranslationAudioRequest)(nil),  // 10: yandex.VideoTranslationAudioRequest
	(*VideoTranslationAudioResponse)(nil), // 11: yandex.VideoTranslationAudioResponse
	(*SubtitlesObject)(nil),               // 12: yandex.SubtitlesObject
	(*SubtitlesRequest)(nil),              // 13: yandex.SubtitlesRequest
	(*SubtitlesResponse)(nil),             // 14: yandex.SubtitlesResponse
	(*StreamTranslationObject)(nil),       // 15: yandex.StreamTranslationObject
	(*StreamTranslationRequest)(nil),      // 16: yandex.StreamTranslationRequest
	(*StreamTranslationResponse)(nil),     // 17: yandex.StreamTranslationResponse
	(*StreamPingRequest)(nil),             // 18: yandex.StreamPingRequest
	(*YandexSessionRequest)(nil),          // 19: yandex.YandexSessionRequest
	(*YandexSessionResponse)(nil),         // 20: yandex.YandexSessionResponse
}
var file_internal_yandexproto_yandex_proto_depIdxs = []int32{
	1,  // 0: yandex.VideoTranslationRequest.translationHelp:type_name -> yandex.VideoTranslationHelpObject
	4,  // 1: yandex.VideoTranslationCacheResponse.default:type_name -> yandex.VideoTranslationCacheItem
	4,  // 2: yandex.VideoTranslationCacheResponse.cloning:type_name -> yandex.VideoTranslationCacheItem
	8,  // 3: yandex.ChunkAudioObject.audioBuffer:type_name -> yandex.PartialAudioBufferObject
	9,  // 4: yandex.VideoTranslationAudioRequest.partialAudioInfo:type_name -> yandex.ChunkAudioObject
	7,  // 5: yandex.VideoTranslationAudioRequest.audioInfo:type_name -> yandex.AudioBufferObject
	12, // 6: yandex.SubtitlesResponse.subtitles:type_name -> yandex.SubtitlesObject
	0,  // 7: yandex.StreamTranslationResponse.interval:type_name -> yandex.StreamInterval
	15, // 8: yandex.StreamTranslationResponse.translatedInfo:type_name -> yandex.StreamTranslationObject
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_internal_yandexproto_yandex_proto_init() }
func file_internal_yandexproto_yandex_proto_init() {
	if File_internal_yandexproto_yandex_proto != nil {
		return
	}
	file_internal_yandexproto_yandex_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_yandexproto_yandex_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_yandexproto_yandex_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_yandexproto_yandex_proto_msgTypes[9].OneofWrappers = []any{}
	file_internal_yandexproto_yandex_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_yandexproto_yandex_proto_rawDesc), len(file_internal_yandexproto_yandex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_yandexproto_yandex_proto_goTypes,
		DependencyIndexes: file_internal_yandexproto_yandex_proto_depIdxs,
		EnumInfos:         file_internal_yandexproto_yandex_proto_enumTypes,
		MessageInfos:      file_internal_yandexproto_yandex_proto_msgTypes,
	}.Build()
	File_internal_yandexproto_yandex_proto = out.File
	file_internal_yandexproto_yandex_proto_goTypes = nil
	file_internal_yandexproto_yandex_proto_depIdxs = nil
}
